#@include file-fluent.conf

apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |-
    ################################################################
    # This source gets all logs from local docker host
    <label @FLUENT_LOG>
      <match fluent.*>
        @type stdout
      </match>
    </label>
    
    <source>
      @type tail
      @id in_tail_container_logs
      path {{.Values.configmap.input.sourcePath}}
      exclude_path [{{.Values.configmap.input.excludePath}}]
      pos_file {{.Values.configmap.input.posFile}}
      tag kubernetes.*
      read_from_head true
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key @timestamp
          time_format %Y-%m-%dT%H:%M:%S.%NZ
        </pattern>
        <pattern>
          format none
          message_key logMessage
        </pattern>
      </parse>
    </source>
    
    <filter kubernetes.**>
      @id filter_kubernetes_metadata
      @type kubernetes_metadata
    </filter>
    
    <filter kubernetes.**>
      @type parser
      key_name log
      reserve_data true
      remove_key_name_field true
      <parse>
        @type json
      </parse>
    </filter>
    
    <match kubernetes.**>
      @type copy
      <store>
        @type file
        path /data/output
      </store>
    
      <store>
        @type stdout
      </store>
    
      <store>
        @type elasticsearch
        @log_level info
        include_tag_key true
    
        host {{.Values.configmap.elastic.host}}
        port {{.Values.configmap.elastic.port}}
        user {{.Values.configmap.elastic.username}}
        password {{.Values.configmap.elastic.password}}
        #cloud_id 25622abc63444ebc814b306bfaea1009:dXMtY2VudHJhbDEuZ2NwLmNsb3VkLmVzLmlvJGRhN2FmMzgzMzVlNjQwMWM5OGI3YTMxN2E3NjM1NTQ1JDI2YTA1YjljM2Y1NjRhOWRhZDY0OTZmYTcyNDk4MjY4
        #cloud_auth 'elastic:2K4zlo7oz4a4857m3VspAf1v'
        scheme https
        ssl_verify false
    
        reload_connections true
        logstash_format true
        logstash_prefix microservice
        logstash_dateformat %Y-%m-%d
      </store>
    </match>