---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-account-service
    version: 0.0.2-apm
  name: ms-account-service
  namespace: apps
spec:
  ports:
    - name: service-port
      port: 80
      targetPort: 8080
      nodePort: 32761
      protocol: TCP
  selector:
    app: account-ms
    version: 0.0.2-apm
  type: NodePort
