apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: account-ms
    version: 0.0.1-mysql
  name: account-ms
  namespace: apps
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: account-ms
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: account-ms
        version: 0.0.1-mysql
    spec:
      containers:
        - image: amsidhmicroservice/ms-account-service:0.0.1-mysql
          imagePullPolicy: IfNotPresent
          name: account-ms
          ports:
            - name: tomcat-port
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: account-ms-configmap
            - secretRef:
                name: account-secret

          livenessProbe:
            httpGet:
              path: "/actuator/health/liveness"
              port: tomcat-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 20
            timeoutSeconds: 10
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: "/actuator/health/readiness"
              port: tomcat-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 20
            timeoutSeconds: 10
            successThreshold: 1

          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1024Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
