namespace:
  name: monitoring
configmap:
  elastic:
    host: "quickstart-es-internal-http.monitoring.svc.cluster.local"
    port: 9200
    username: elastic
    password: "20ZITwPakX0ma0756EK7r6q2"
    schema: https
    ssl_verify: false
    ssl_version: TLSv1_2
    logstash_prefix: ${record['kubernetes']['container_name']}

  input:
    source:
      includePaths:
        - /var/log/containers/ms-card-service*.log
        - /var/log/containers/ms-account-service*.log
        - /var/log/containers/ms-location-service*.log
        - /var/log/containers/ms-address-service*.log
        - /var/log/containers/ms-person-service*.log
      excludePaths:
        - '"/var/log/containers/fluent*.log"'
        - '"/var/log/containers/*kibana*.log"'
        - '"/var/log/containers/*elastic*.log"'
      posFilePath: /var/log/fluentd-container.log.pos
