---
apiVersion: v1
kind: ConfigMap
metadata:
  name: card-ms-configmap
  labels:
    app: card-ms-configmap
data:
  SPRING_PROFILES_ACTIVE: {{.Values.configmap.activeProfile}}
  APPLICATION_PORT: "8080"
  POSTGRES_DATABASE_HOST: "postgres"
  POSTGRES_DATABASE_PORT: "5432"
  POSTGRES_DATABASE: "postgresdb"
  POSTGRES_USERNAME: "postgres"

