apiVersion: skaffold/v2beta18
kind: Config

build:
  local:
    concurrency: 0

requires:
  - path: ./card-service
  - path: ./account-service
  - path: ./location-service
  - path: ./address-service
  - path: ./person-service


