apiVersion: skaffold/v2beta18
kind: Config

deploy:
  #kubectl:
  #  manifests: ["deployment/devtool/efk/elasticsearch-kibana/1-crds.yaml","deployment/devtool/efk/elasticsearch-kibana/2-operator.yaml"]

  helm:
    releases:
      - name: elastic-release
        chartPath: helm/elastic-chart
        namespace: monitoring
        createNamespace: true
        upgradeOnChange: true

      - name: fluentd-release
        remoteChart: fluentd
        repo: https://charts.bitnami.com/bitnami
        valuesFiles: [helm/bitnami-fluentd-chart/values.yaml]
        namespace: monitoring
        createNamespace: true
        upgradeOnChange: true
        # helm upgrade --install fluentd-release bitnami/fluentd -f values.yaml


profiles:
  # use the cloudbuild profile to build images using Google Cloud Build
  - name: cloudbuild
    build:
      googleCloudBuild: { }
