apiVersion: skaffold/v2beta18
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "0.0.1-mysql"
  local:
    concurrency: 0
    push: false

  artifacts:
    - image: docker.io/amsidhmicroservice/ms-card-service
      context: ms-card-service
      docker:
        dockerfile: Dockerfile
        noCache: true
        cacheFrom:
          - docker.io/amsidhmicroservice/ms-card-service

    - image: docker.io/amsidhmicroservice/ms-account-service
      context: ms-account-service
      docker:
        dockerfile: Dockerfile
        noCache: true
        cacheFrom:
          - docker.io/amsidhmicroservice/ms-account-service

    - image: docker.io/amsidhmicroservice/ms-location-service
      context: ms-location-service
      docker:
        dockerfile: Dockerfile
        noCache: true
        cacheFrom:
          - docker.io/amsidhmicroservice/ms-location-service

    - image: docker.io/amsidhmicroservice/ms-address-service
      context: ms-address-service
      docker:
        dockerfile: Dockerfile
        noCache: true
        cacheFrom:
          - docker.io/amsidhmicroservice/ms-address-service

    - image: docker.io/amsidhmicroservice/ms-person-service
      context: ms-person-service
      docker:
        dockerfile: Dockerfile
        noCache: true
        cacheFrom:
          - docker.io/amsidhmicroservice/ms-person-service
