apiVersion: skaffold/v2beta18
kind: Config
build:
  tagPolicy:
    sha256: { }
  local:
    concurrency: 0
    push: true
  artifacts:
    - image: ms-card-service
      context: ms-card-service
      jib:
        fromImage: openjdk:19-alpine@sha256:1686909f4ca66f3e13463e2b00a1c53808aa155f81ae9a8aad8f4b89420d91ef
    - image: ms-account-service
      context: ms-account-service
      jib:
        fromImage: openjdk:19-alpine@sha256:1686909f4ca66f3e13463e2b00a1c53808aa155f81ae9a8aad8f4b89420d91ef
    - image: ms-location-service
      context: ms-location-service
      jib:
        fromImage: openjdk:19-alpine@sha256:1686909f4ca66f3e13463e2b00a1c53808aa155f81ae9a8aad8f4b89420d91ef
    - image: ms-address-service
      context: ms-address-service
      jib:
        fromImage: openjdk:19-alpine@sha256:1686909f4ca66f3e13463e2b00a1c53808aa155f81ae9a8aad8f4b89420d91ef

    - image: ms-person-service
      context: ms-person-service
      jib:
        fromImage: openjdk:19-alpine@sha256:1686909f4ca66f3e13463e2b00a1c53808aa155f81ae9a8aad8f4b89420d91ef

deploy:
#  kubectl:
#    manifests:
#    - deployment/devtool/gateway/1-ingress-controller.yaml
#    - deployment/devtool/gateway/2-ingress-gateway.yaml
  helm:
    releases:
    - name: ms-card-service-chart
      chartPath: helm/ms-card-service/
    - name: ms-account-service-chart
      chartPath: helm/ms-account-service/
    - name: ms-location-service-chart
      chartPath: helm/ms-location-service/
    - name: ms-address-service-chart
      chartPath: helm/ms-address-service/
    - name: ms-person-service-chart
      chartPath: helm/ms-person-service/

profiles:
  # use the cloudbuild profile to build images using Google Cloud Build
  - name: cloudbuild
    build:
      googleCloudBuild: { }
