apiVersion: skaffold/v2beta18
kind: Config

deploy:
  #kubectl:
  #  manifests: ["deployment/devtool/efk/elasticsearch-kibana/1-crds.yaml","deployment/devtool/efk/elasticsearch-kibana/2-operator.yaml"]

  helm:
    releases:
      - name: elastic-release
        chartPath: helm/elastic-chart
        namespace: monitoring
        createNamespace: true
        upgradeOnChange: true

      - name: kibana-release
        chartPath: helm/kibana-chart
        namespace: monitoring
        createNamespace: true
        upgradeOnChange: true

profiles:
  # use the cloudbuild profile to build images using Google Cloud Build
  - name: cloudbuild
    build:
      googleCloudBuild: { }
