apiVersion: skaffold/v2beta18
kind: Config
build:
  tagPolicy:
    sha256: { }
  local:
    concurrency: 0

  artifacts:
    - image: card-service
      context: card-service
      docker:
        dockerfile: Dockerfile

    - image: account-service
      context: account-service
      docker:
        dockerfile: Dockerfile

    - image: location-service
      context: location-service
      docker:
        dockerfile: Dockerfile

    - image: address-service
      context: address-service
      docker:
        dockerfile: Dockerfile

    - image: person-service
      context: person-service
      docker:
        dockerfile: Dockerfile

deploy:
  kubectl:
    manifests:
      - deployment/services/card-service/*.yaml
      - deployment/services/account-service/*.yaml
      - deployment/services/location-service/*.yaml
      - deployment/services/address-service/*yaml
      - deployment/services/person-service/*.yaml

profiles:
  # use the cloudbuild profile to build images using Google Cloud Build
  - name: cloudbuild
    build:
      googleCloudBuild: { }
  - name: dockerfile
    build:
      artifacts:
        - image: card-service
          context: card-service
          docker:
            dockerfile: Dockerfile

        - image: account-service
          context: account-service
          docker:
            dockerfile: Dockerfile

        - image: location-service
          context: location-service
          docker:
            dockerfile: Dockerfile

        - image: address-service
          context: address-service
          docker:
            dockerfile: Dockerfile

        - image: person-service
          context: person-service
          docker:
            dockerfile: Dockerfile
