apiVersion: skaffold/v2beta18
kind: Config
build:
  tagPolicy:
    sha256: { }
  local:
    concurrency: 0
    push: false
  artifacts:
    - image: card-service
      context: card-service
      jib:
        fromImage: openjdk:19-alpine
    - image: account-service
      context: account-service
      jib:
        fromImage: openjdk:19-alpine
    - image: location-service
      context: location-service
      jib:
        fromImage: openjdk:19-alpine
    - image: address-service
      context: address-service
      jib:
        fromImage: openjdk:19-alpine
    - image: person-service
      context: person-service
      jib:
        fromImage: openjdk:19-alpine

deploy:
  kubectl:
    manifests:
    - deployment/devtool/gateway/2-ingress-gateway.yaml
  helm:
    releases:
    - name: card-service-chart
      chartPath: helm/card-service/
    - name: account-service-chart
      chartPath: helm/account-service/
    - name: location-service-chart
      chartPath: helm/location-service/
    - name: address-service-chart
      chartPath: helm/address-service/
    - name: person-service-chart
      chartPath: helm/person-service/

profiles:
  # use the cloudbuild profile to build images using Google Cloud Build
  - name: cloudbuild
    build:
      googleCloudBuild: { }
