apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: microservice
build:
  tagPolicy:
    sha256: { }
  local:
    push: true
  artifacts:
  - image: amsidhmicroservice/card-service
    context: card-service
    docker:
      dockerfile: Dockerfile

  - image: amsidhmicroservice/account-service
    context: account-service
    docker:
      dockerfile: Dockerfile

  - image: amsidhmicroservice/location-service
    context: location-service
    docker:
      dockerfile: Dockerfile

  - image: amsidhmicroservice/address-service
    context: address-service
    docker:
      dockerfile: Dockerfile

  - image: amsidhmicroservice/person-service
    context: person-service
    docker:
      dockerfile: Dockerfile
manifests:
  rawYaml:
  - deployment/services/card-service/card-service-configmap.yaml
  - deployment/services/card-service/card-service-deployment.yaml

  - deployment/services/account-service/account-service-configmap.yaml
  - deployment/services/account-service/account-service-deployment.yaml

  - deployment/services/location-service/location-service-configmap.yaml
  - deployment/services/location-service/location-service-deployment.yaml

  - deployment/services/address-service/address-service-configmap.yaml
  - deployment/services/address-service/address-service-deployment.yaml

  - deployment/services/person-service/person-service-configmap.yaml
  - deployment/services/person-service/person-service-deployment.yaml
