apiVersion: skaffold/v2beta18
kind: Config
build:
  tagPolicy:
    sha256: { }
  local:
    concurrency: 0
    push: true
  artifacts:
    - image: docker.io/amsidhmicroservice/ms-card-service
      context: ms-card-service
      jib:
        fromImage: openjdk:19-alpine@sha256:1686909f4ca66f3e13463e2b00a1c53808aa155f81ae9a8aad8f4b89420d91ef
    - image: docker.io/amsidhmicroservice/ms-account-service
      context: ms-account-service
      jib:
        fromImage: openjdk:19-alpine@sha256:1686909f4ca66f3e13463e2b00a1c53808aa155f81ae9a8aad8f4b89420d91ef
    - image: docker.io/amsidhmicroservice/ms-location-service
      context: ms-location-service
      jib:
        fromImage: openjdk:19-alpine@sha256:1686909f4ca66f3e13463e2b00a1c53808aa155f81ae9a8aad8f4b89420d91ef
    - image: docker.io/amsidhmicroservice/ms-address-service
      context: ms-address-service
      jib:
        fromImage: openjdk:19-alpine@sha256:1686909f4ca66f3e13463e2b00a1c53808aa155f81ae9a8aad8f4b89420d91ef

    - image: docker.io/amsidhmicroservice/ms-person-service
      context: ms-person-service
      jib:
        fromImage: openjdk:19-alpine@sha256:1686909f4ca66f3e13463e2b00a1c53808aa155f81ae9a8aad8f4b89420d91ef
