apiVersion: skaffold/v2beta18
kind: Config
build:
  tagPolicy:
    sha256: { }
  local:
    concurrency: 0
  artifacts:
    - image: card-service
      context: card-service
      jib:
        fromImage: openjdk:19-alpine
    - image: account-service
      context: account-service
      jib:
        fromImage: openjdk:19-alpine
    - image: location-service
      context: location-service
      jib:
        fromImage: openjdk:19-alpine
    - image: address-service
      context: address-service
      jib:
        fromImage: openjdk:19-alpine
    - image: person-service
      context: person-service
      jib:
        fromImage: openjdk:19-alpine

deploy:
  kubectl:
    manifests:
    - deployment/services/card-service/*.yaml
    - deployment/services/account-service/*.yaml
    - deployment/services/location-service/*.yaml
    - deployment/services/address-service/*.yaml
    - deployment/services/person-service/*.yaml

profiles:
  # use the cloudbuild profile to build images using Google Cloud Build
  - name: cloudbuild
    build:
      googleCloudBuild: { }
