---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.service.name}}
    version: {{.Values.version}}
  name: {{.Values.service.name}}
spec:
  ports:
    - name: account-http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{.Values.deployment.name}}
    version: {{.Values.version}}
  type: {{.Values.service.type}}
