---
apiVersion: v1
kind: ConfigMap
metadata:
  name: address-ms-configmap
  labels:
    app: address-ms-configmap
data:
  SPRING_PROFILES_ACTIVE: {{.Values.configmap.SPRING_PROFILES_ACTIVE}}
  APPLICATION_PORT: "{{.Values.configmap.APPLICATION_PORT}}"
  DATABASE_NAME: {{.Values.configmap.DATABASE_NAME}}
  DATABASE_USERNAME: {{.Values.configmap.DATABASE_USERNAME}}
  DATABASE_PASSWORD: {{.Values.configmap.DATABASE_PASSWORD}}
  REDIS_HOST: {{.Values.configmap.REDIS_HOST}}
  REDIS_PORT: "{{.Values.configmap.REDIS_PORT}}"
  REDIS_USERNAME: {{.Values.configmap.REDIS_USERNAME}}
  REDIS_PASSWORD: {{.Values.configmap.REDIS_PASSWORD}}
  ZIPKIN_HOST: {{.Values.configmap.ZIPKIN_HOST}}



