---
apiVersion: v1
kind: ConfigMap
metadata:
  name: person-ms-configmap
  labels:
    app: person-ms-configmap
data:
  SPRING_PROFILES_ACTIVE: {{.Values.configmap.activeProfile}}
  APPLICATION_PORT: "8080"
  DATABASE_NAME: microservice
  DATABASE_USERNAME: sa
  DATABASE_PASSWORD: ""

