---
apiVersion: v1
data:
  elasticsearch.password: {{.Values.data.elasticsearch.password}}
kind: Secret
metadata:
  name: kibana-elasticsearch-credentials

---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{.Values.deployment.name}}
spec:
  version: {{.Values.deployment.imageName}}
  count: {{.Values.deployment.numberOfReplicas}}
  elasticsearchRef:
    name: {{.Values.deployment.name}}
  elasticsearch.username: {{.Values.data.elasticsearch.username}}
  secureSettings:
    - secretName: kibana-elasticsearch-credentials
  http:
    service:
      spec:
        type: {{.Values.service.type}}