---
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: {{.Values.deployment.name}}
spec:
  version: {{.Values.deployment.imageTag}}
  count: {{.Values.deployment.numberOfReplicas}}
  elasticsearchRef:
    name: {{.Values.deployment.name}}
  podTemplate:
    spec:
      automountServiceAccountToken: true
  config:
    concurrent_requests: 5
    rum:
      enabled: true
    queue.mem.events: 4096
    max_procs: 4
    output:
      elasticsearch:
        username: {{.Values.elasticsearch.username}}
        password: {{.Values.elasticsearch.password}}
        protocol: {{.Values.elasticsearch.protocol}}
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      spec:
        type: {{.Values.service.type}}