apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: person-ms
    version: 0.0.2-apm
  name: person-ms
  namespace: apps
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: person-ms
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: person-ms
        version: 0.0.2-apm
    spec:
      containers:
        - image: amsidhmicroservice/ms-person-service:0.0.2-apm
          imagePullPolicy: IfNotPresent
          name: person-ms
          ports:
            - name: tomcat-http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: person-ms-configmap
            - secretRef:
                name: person-secret
          livenessProbe:
            httpGet:
              path: "/actuator/health/liveness"
              port: tomcat-http
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 20
            timeoutSeconds: 10
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: "/actuator/health/readiness"
              port: tomcat-http
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 20
            timeoutSeconds: 10
            successThreshold: 1

          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1024Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
