---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-person-service
    version: 0.0.2-apm
  name: ms-person-service
  namespace: apps
spec:
  ports:
    - name: service-port
      port: 80
      targetPort: 8080
      nodePort: 32765
      protocol: TCP
  selector:
    app: person-ms
    version: 0.0.2-apm
  type: NodePort
