management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: GET,POST,PUT,DELETE

  httpexchanges:
    recording:
      include: time_taken,session_id,response_headers,request_headers,principal,remote_address,cookie_headers,authorization_header
      enabled: true
  endpoint:
    health:
      enabled: true
      show-details: always

logging:
  level:
    root: info
    com.amsidh.mvc: info
    com.amsidh.mvc.client.feign: debug
    # Log all sql queries
    sql: debug
    # Log sql query parameters
    org.hibernate.orm.jdbc.bind: trace
    # Log hibernate statistics
    org.hibernate.stat: debug
    # Log cache operations
    org.hibernate.cache: debug
    # Logging Configuration for Production set the logging.level.org.hibernate: ERROR

spring:
  jpa:
    properties:
      hibernate:
        # Generate hibernate statistics
        # Logging Configuration for Production set the generate_statistics: false
        generate_statistics: true
        # Log slow queries
        session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 1
  data:
    redis:
      host: ${REDIS_HOST:redis.redis.svc.cluster.local}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:userredis}
      password: ${REDIS_PASSWORD:Redis@123}
#      host: localhost
#      port: 6379
#      username: userredis
#      password: Redis@123
