---
apiVersion: v1
kind: ConfigMap
metadata:
  name: location-ms-configmap
  labels:
    app: location-ms-configmap
data:
  SPRING_PROFILES_ACTIVE: {{.Values.configmap.activeProfile}}
  APPLICATION_PORT: "8080"
  DATABASE_NAME: microservice
  DATABASE_USERNAME: sa
  DATABASE_PASSWORD: ""
  REDIS_HOST: "redis.redis.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_USERNAME: "myredis"
  REDIS_PASSWORD: "Redis@123"
  ZIPKIN_HOST: "zipkin-service.monitoring.svc.cluster.local"
