---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-card-service
    version: 0.0.2-apm
  name: ms-card-service
  namespace: apps
spec:
  ports:
    - name: service-port
      port: 80
      targetPort: 8080
      nodePort: 32763
      protocol: TCP

  selector:
    app: card-ms
    version: 0.0.2-apm
  type: NodePort
