apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: card-ms
    version: 0.0.5-SNAPSHOT
  name: card-ms
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: card-ms
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: card-ms
        version: 0.0.5-SNAPSHOT
    spec:
      containers:
        - image: amsidhmicroservice/ms-card-service
          imagePullPolicy: IfNotPresent
          name: card-ms
          ports:
            - name: card-http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: card-ms-configmap
            - secretRef:
                name: card-secret
          livenessProbe:
            httpGet:
              path: "/actuator/health/liveness"
              port: 8080
            failureThreshold: 5
            periodSeconds: 30
            initialDelaySeconds: 180
            timeoutSeconds: 30
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: "/actuator/health/readiness"
              port: 8080
            failureThreshold: 10
            periodSeconds: 120
            initialDelaySeconds: 240
            timeoutSeconds: 30
            successThreshold: 1

          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1024Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
