---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-card-service
    version: 0.0.1-SNAPSHOT
  name: ms-card-service
spec:
  ports:
    - name: card-http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: card-ms
    version: 0.0.1-SNAPSHOT
  type: NodePort
