---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.service.name}}
    version: {{.Values.version}}
  name: {{.Values.service.name}}
  namespace: {{.Values.namespace}}
spec:
  ports:
    - port: {{default "80" .Values.service.port}}
      targetPort: {{default "8080" .Values.service.targetPort}}
      protocol: {{default "TCP" .Values.service.protocol}}
  selector:
    app: {{.Values.deployment.name}}
    version: {{.Values.version}}
  type: {{.Values.service.type}}
