apiVersion: skaffold/v2beta18
kind: Config
build:
  tagPolicy:
    sha256: { }
  artifacts:
  - image: person-service
    context: .
    docker:
      dockerfile: Dockerfile

# defines the Kubernetes manifests to deploy on each run
deploy:
  kubectl:
    manifests:
    - ../deployment/services/person-service/person-*.yaml

profiles:
  # use the cloudbuild profile to build images using Google Cloud Build
  - name: cloudbuild
    build:
      googleCloudBuild: {}
  # use the dockerfile profile to build images using Docker instead of Jib
  - name: dockerfile
    build:
      artifacts:
        - image: person-service
          context: .
