---
apiVersion: v1
kind: ConfigMap
metadata:
  name: card-ms-configmap
  labels:
    app: card-ms-configmap
data:
  SPRING_PROFILES_ACTIVE: "prod"
  APPLICATION_PORT: "8080"
  DATABASE_NAME: microservice
  DATABASE_USERNAME: sa
  DATABASE_PASSWORD: ""

