apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: card-ms
    version: latest
  name: card-ms
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: card-ms
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: card-ms
        version: latest
    spec:
      containers:
        - image: amsidhmicroservice/card-service:latest
          imagePullPolicy: IfNotPresent
          name: card-ms
          ports:
            - name: liveness-port
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: card-ms-configmap
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1024Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: card-service
    version: latest
  name: card-service
spec:
  ports:
    - name: http
      port: 8085
      targetPort: 8080
      nodePort: 32100
      protocol: TCP
  selector:
    app: card-ms
    version: latest
  type: LoadBalancer
