---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: card-service
    version: latest
  name: card-service
spec:
  ports:
    - name: card-http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: card-ms
    version: latest
  type: LoadBalancer
