apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: monitoring
spec:
  version: 6.8.23
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
  http:
    service:
      spec:
        type: LoadBalancer