apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  namespace: monitoring
spec:
  version: 6.8.23
  count: 1
  elasticsearchRef:
    name: quickstart

  http:
    service:
      spec:
        type: LoadBalancer