apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
stringData:
  users: |-
    amsidh:Amsidh@123
    anjali:Anjali@123
    adithi:Adithi@123
    aditya:Aditya@123
    elastic:Elastic@123
  users_roles: |-
    admin:amsidh,elastic
    power_user:amsidh,anjali
    user:anjali,adithi,aditya