---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-credentials
stringData:
  username: elastic    # required field for kubernetes.io/basic-auth
  password: Elastic@123 # required field for kubernetes.io/basic-auth
  roles: ingest_admin,kibana_admin  # optional, not part of kubernetes.io/basic-auth

---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{.Values.deployment.name}}
spec:
  version: {{.Values.deployment.imageName}}
  auth:
    fileRealm:
      - secretName: elasticsearch-credentials
  nodeSets:
    - name: default
      count: {{.Values.deployment.numberOfReplicas}}
      config:
        node.store.allow_mmap: false
  http:
    service:
      spec:
        type: {{.Values.service.type}}
