---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: location-service
    version: 0.0.4-SNAPSHOT
  name: location-service
spec:
  ports:
    - port: 80
      targetPort: location-http
  selector:
    app: location-ms
    version: 0.0.4-SNAPSHOT
  type: ClusterIP
