apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: location-service
    version: 0.0.2-SNAPSHOT
  name: location-service
  namespace: default
spec:
  replicas: 2
  minReadySeconds: 45
  selector:
    matchLabels:
      app: location-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: location-service
        version: 0.0.2-SNAPSHOT
    spec:
      containers:
        - image: amsidhmicroservice/location-service:0.0.2-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: location-service
          ports:
            - name: liveness-port
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: location-service-configmap
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1024Mi
          readinessProbe:
            httpGet:
              path: /health
              port: liveness-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
          livenessProbe:
            httpGet:
              path: /health
              port: liveness-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: location-service
    version: 0.0.2-SNAPSHOT
  name: location-service
spec:
  ports:
    - name: http
      port: 8083
      targetPort: 8080
      nodePort: 32103
      protocol: TCP
  selector:
    app: location-service
    version: 0.0.2-SNAPSHOT
  type: LoadBalancer
