---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: location-service
    version: latest
  name: location-service
spec:
  ports:
    - name: location-http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: location-ms
    version: latest
  type: LoadBalancer
