---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: location-service
    version: 0.0.4-SNAPSHOT
  name: location-service
spec:
  ports:
    - name: location-http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: location-ms
    version: 0.0.4-SNAPSHOT
  type: NodePort
