apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: location-ms
    version: latest
  name: location-ms
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: location-ms
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: location-ms
        version: latest
    spec:
      containers:
        - image: amsidhmicroservice/location-service:latest
          imagePullPolicy: IfNotPresent
          name: location-ms
          ports:
            - name: liveness-port
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: location-ms-configmap
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1024Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
