#@include file-fluent.conf

apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  
data:
  fluent.conf: |-
    ################################################################
    # This source gets all logs from local docker host
    <match fluent.**>
      @type null
    </match>
    
    <source>
      @type tail
      @id in_tail_container_logs
      path /var/log/containers/counter*.log,/var/log/containers/person*.log,/var/log/containers/account*.log,/var/log/containers/card*.log,/var/log/containers/address*.log,,/var/log/containers/location*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>
    
    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>
    
    <match **>
      @type elasticsearch_dynamic
      @log_level info
      include_tag_key true
      
      host quickstart-es-internal-http
      port 9200
      user elastic
      password ZWVYAy18tif0p2LX97DA4470
      scheme https
      ssl_verify false
    
      reload_connections true
      logstash_format true
      logstash_prefix ${record['kubernetes']['pod_name']}
    </match>