#@include file-fluent.conf

apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |-
    ################################################################
    # This source gets all logs from local docker host
    <label @FLUENT_LOG>
      <match fluent.*>
        @type stdout
      </match>
    </label>
    
    <source>
      @type tail
      @id in_tail_container_logs
      path /var/log/containers/counter*.log,/var/log/containers/person*.log,/var/log/containers/account*.log,/var/log/containers/card*.log,/var/log/containers/address*.log,,/var/log/containers/location*.log,/var/log/containers/currency*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type regexp
        expression ^(?<time>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.[^Z]*Z)\s(?<stream>[^\s]+)\s(?<character>[^\s])\s(?<log>.*)$
      </parse>
    </source>

    <filter kubernetes.**>
      @type parser
      key_name "log"
      reserve_data true
      <parse>
        @type json
      </parse>
    </filter>
    
    <filter kubernetes.**>
      @id filter_kubernetes_metadata
      @type kubernetes_metadata
    </filter>
    
    <match **>
      @type elasticsearch_dynamic
      @log_level info
      include_tag_key true
      
      host quickstart-es-internal-http
      port 9200
      user elastic
      password 57Y48yjVWPwh33F63wY96LnN
      scheme https
      ssl_verify false
    
      reload_connections true
      logstash_format true
      logstash_prefix ${record['kubernetes']['pod_name']}
    </match>