apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.deployment.name}}
    version: {{.Values.version}}
  name: {{.Values.deployment.name}}
  namespace: {{.Values.namespace}}
spec:
  replicas: {{.Values.deployment.numberOfReplicas}}
  minReadySeconds: 45
  selector:
    matchLabels:
      app: {{.Values.deployment.name}}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{.Values.deployment.name}}
        version: {{.Values.version}}
    spec:
      containers:
        - image: {{.Values.deployment.imageName}}
          imagePullPolicy: IfNotPresent
          name: {{.Values.deployment.name}}
          ports:
            - name: person-http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: person-ms-configmap
            - secretRef:
                name: person-secret
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1024Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
