apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.deployment.name}}
    version: {{.Values.version}}
  name: {{.Values.deployment.name}}
  namespace: {{.Values.namespace}}
spec:
  replicas: {{.Values.deployment.numberOfReplicas}}
  minReadySeconds: 45
  selector:
    matchLabels:
      app: {{.Values.deployment.name}}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{.Values.deployment.name}}
        version: {{.Values.version}}
    spec:
      containers:
        - image: {{.Values.deployment.imageName}}:{{ default "latest" .Values.deployment.imageTag }}
          imagePullPolicy: {{.Values.deployment.imagePullPolicy}}
          name: {{.Values.deployment.name}}
          ports:
            - containerPort: {{default "8080" .Values.deployment.port}}
              protocol: {{default "TCP" .Values.service.protocol}}
          envFrom:
            - configMapRef:
                name: {{default "address-ms-configmap" .Values.configmap.name}}
            - secretRef:
                name: {{default "address-secret" .Values.secret.name}}
          livenessProbe:
            httpGet:
              path: {{default "/actuator/health/liveness" .Values.deployment.livenessProbe.httpGet.path}}
              port: {{default "8080" .Values.deployment.port}}
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 20
            timeoutSeconds: 10
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: {{default "/actuator/health/readiness" .Values.deployment.readinessProbe.httpGet.path}}
              port: {{default "8080" .Values.deployment.port}}
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 20
            timeoutSeconds: 10
            successThreshold: 1

          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1024Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
