apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{.Values.persistent.spec.storageClassName}}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete