apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name}}
spec:
  clusterIP: {{.Values.service.clusterIP}}
  ports:
    - port: {{.Values.service.port}}
      targetPort: {{.Values.service.port}}
      name: redis
  selector:
    app: {{.Values.deployment.name}}