# Persistent Volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-database-data-volume
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi