apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: {{.Values.namespace.name}}
data:
  fluent.conf: |-
    ################################################################
    <system>
      root_dir /tmp/fluentd-buffers/
    </system>
    <label @FLUENT_LOG>
      <match fluent.**>
        @type stdout
      </match>
    </label>

    ### Source input for all microservices ####
    <source>
      @id source-ms-id
      @type tail
      path {{ join "," .Values.configmap.input.source.includePaths }}
      pos_file {{.Values.configmap.input.source.posFilePath}}
      exclude_path [{{join "," .Values.configmap.input.source.excludePaths}}]
      tag  raw.kubernetes.*
      read_from_head true
      refresh_interval 5s
      encoding UTF-8
      <parse>
        @type multi_format
        <pattern>
          format json
          time_format %Y-%m-%dT%H:%M:%S.%NZ
          time_type string
          keep_time_key false
        </pattern>
        <pattern>
          format regexp
          expression /^(?<@timestamp>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
          time_format %Y-%m-%dT%H:%M:%S.%N%:z
          keep_time_key false
        </pattern>
        <pattern>
          format none
        </pattern>
      </parse>
    </source>

    # Detect exceptions in the log output and forward them as one log entry.
    <match raw.kubernetes.**>
      @id detect_exceptions_id
      @type detect_exceptions
      remove_tag_prefix raw
      message log
      stream stream
      multiline_flush_interval 5
      max_bytes 500000
      max_lines 1000
    </match>
    
    <filter kubernetes.**>
      @id filter_kubernetes_metadata_id
      @type kubernetes_metadata
      allow_orphans false
      skip_labels true
      skip_container_metadata true
      skip_master_url true
      skip_namespace_metadata true
    </filter>

    <filter kubernetes.**>
      @type parser
      key_name log
      reserve_data true
      remove_key_name_field true
      <parse>
        @type json
      </parse>
    </filter>

    <match **>
      @id multi_target
      @type copy
      <store>
        @id ms-elastic-store
        @type elasticsearch_dynamic
        @log_level debug
        include_tag_key true
        time_key_exclude_timestamp false

        host {{.Values.configmap.elastic.host}}
        port {{.Values.configmap.elastic.port}}
        user {{.Values.configmap.elastic.username}}
        password {{.Values.configmap.elastic.password}}
        #cloud_id 25622abc63444ebc814b306bfaea1009:dXMtY2VudHJhbDEuZ2NwLmNsb3VkLmVzLmlvJGRhN2FmMzgzMzVlNjQwMWM5OGI3YTMxN2E3NjM1NTQ1JDI2YTA1YjljM2Y1NjRhOWRhZDY0OTZmYTcyNDk4MjY4
        #cloud_auth 'elastic:2K4zlo7oz4a4857m3VspAf1v'
        scheme {{.Values.configmap.elastic.schema}}
        ssl_version {{.Values.configmap.elastic.ssl_version}}
        ssl_verify {{.Values.configmap.elastic.ssl_verify}}
        suppress_type_name true
        logstash_format true
        logstash_prefix {{.Values.configmap.elastic.logstash_prefix}}
        logstash_dateformat %Y.%m.%d
        type_name fluentd
        reconnect_on_error true
        reload_on_failure false
        reload_connections false
        slow_flush_log_threshold 25.0
        <buffer tag>
          @type file
          path /var/log/fluentd-buffers/ms-service
          total_limit_size 1024MB
          flush_mode interval
          retry_type exponential_backoff
          flush_thread_count 20
          flush_interval 5s
          retry_timeout 1m
          retry_max_interval 30
          chunk_limit_size 10M
          queue_limit_length 8
          overflow_action drop_oldest_chunk
          timekey 0.1h
        </buffer>
      </store>
      <store>
        @id copyToFile
        @type file
        path  /var/log/copy-log
        compress gzip
        <format>
          localtime false
        </format>
        <buffer time>
          timekey_wait 10m
          timekey 86400
          timekey_use_utc true
          path  /var/log/copy-log
        </buffer>
        <inject>
          localtime false
        </inject>
      </store>
    </match>

