apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: account-service
    version: 0.0.2-SNAPSHOT
  name: account-service
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: account-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: account-service
        version: 0.0.2-SNAPSHOT
    spec:
      containers:
        - image: amsidhmicroservice/account-service:0.0.2-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: account-service
          ports:
            - name: liveness-port
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: account-service-configmap
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1024Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: account-service
    version: 0.0.2-SNAPSHOT
  name: account-service
spec:
  ports:
    - name: http
      port: 8084
      targetPort: 8080
      nodePort: 32101
      protocol: TCP
  selector:
    app: account-service
    version: 0.0.2-SNAPSHOT
  type: LoadBalancer
