---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: account-service
    version: 0.0.4-SNAPSHOT
  name: account-service
spec:
  ports:
    - port: 80
      targetPort: account-http
  selector:
    app: account-ms
    version: 0.0.4-SNAPSHOT
  type: ClusterIP
