---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: account-service
    version: 0.0.4-SNAPSHOT
  name: account-service
spec:
  ports:
    - name: account-http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: account-ms
    version: 0.0.4-SNAPSHOT
  type: NodePort
