---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: person-service
    version: 0.0.4-SNAPSHOT
  name: person-service
spec:
  ports:
    - port: 80
      targetPort: person-http
  selector:
    app: person-ms
    version: 0.0.4-SNAPSHOT
  type: LoadBalancer
