apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: person-ms
    version: 0.0.4-SNAPSHOT
  name: person-ms
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: person-ms
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: person-ms
        version: 0.0.4-SNAPSHOT
    spec:
      containers:
        - image: person-service
          imagePullPolicy: IfNotPresent
          name: person-ms
          ports:
            - name: person-http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: person-ms-configmap
            - secretRef:
                name: person-secret
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1024Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
