apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zipkin
  name: zipkin
  namespace: monitoring
spec:
  replicas: 1
  minReadySeconds: 60
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - image: openzipkin/zipkin
          name: zipkin
          ports:
            - name: zipkin-http
              containerPort: 9411
          resources:
            requests:
              cpu: 200m
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zipkin
  name: zipkin-service
  namespace: monitoring
spec:
  ports:
    - name: zipkin-http
      port: 9411
      targetPort: 9411
      protocol: TCP
  selector:
    app: zipkin
  type: LoadBalancer