server:
  port: ${APPLICATION_PORT:0}


spring:
  application:
    name: ms-account-service
  profiles:
    include:
      - common
    active: ${SPRING_PROFILES_ACTIVE:dev}

# All traces should be sent to latency analysis tool
management:
  tracing:
    sampling:
      probability: 1.0


---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:${DATABASE_NAME:microservice};DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      generate_statistics: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:postgresdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
  jpa:
    show-sql: false
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:postgresdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
  jpa:
    show-sql: false
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
