# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: 1-microservice-build-push-sonarqube-workflow

on:
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

jobs:
  build_clean_install_push_job:
    name: build_clean_install_push_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project repository
        uses: actions/checkout@v2
      - name: Setup Java 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{env.DOCKER_USERNAME}}
          password: ${{env.DOCKER_PASSWORD}}
      - name: Maven Clean, Install, Docker Build, Push and SonarCloud
        run: mvn -B clean install -Dsonar.login=${{secrets.SONAR_TOKEN}}  -P build-push,sonar --file pom.xml
