name: Skaffold
on:
  push:
    paths:
      - src/**
      - .github/workflows/ci.yml
  workflow_dispatch:

jobs:
  build:
    name: Skaffold Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: "temurin"
          cache: "maven"

      - name: Maven Clean, Install
        run: mvn clean install -DskipTests

      - name: Cache layers
        uses: actions/cache@v3
        with:
          path: "${{ github.workspace }}/.skaffold/cache"
          key: skaffold-${{ hashFiles('**/cache') }}
          restore-keys: |
            skaffold-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: "registry-1.docker.io"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        uses: hiberbee/github-action-skaffold@latest
        with:
          command: build
          filename: skaffold.yaml
          working-directory: ${{ github.workspace }}
          skip-tests: true

