name: Skaffold
on:
  push:
    paths:
      - src/**
      - .github/workflows/ci.yml
  workflow_dispatch:
jobs:
  build:
    name: Skaffold Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: "temurin"
          cache: "maven"

      - name: Maven Clean, Install
        run: mvn clean install

      - name: Cache layers
        uses: actions/cache@v3
        with:
          path: "${{ github.workspace }}/.skaffold/cache"
          key: skaffold-${{ hashFiles('**/cache') }}
          restore-keys: |
            skaffold-

      - name: Run Skaffold pipeline as command
        uses: hiberbee/github-action-skaffold@latest
        id: build
        with:
          command: build
          working-directory: ${{ github.workspace }}
          skip-tests: false
          repository: ${{ secrets.SKAFFOLD_DEFAULT_REPO }}

      - name: Run Skaffold with output to JSON
        uses: hiberbee/github-action-skaffold@latest
        with:
          command: build
          file-output: tags.json
          repository: ${{ secrets.DOCKER_REPOSITORY }}
          working-directory: ${{ github.workspace }}

      - name: Read JSON file output
        run: cat tags.json
        working-directory: ${{ github.workspace }}

      - name: Read JSON step output
        run: echo '${{ steps.build.outputs.output }}'

