# Builds
name: java-maven-skaffold-build-push-docker
on:
  workflow_dispatch:
jobs:
  build-push-skaffold:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '.'
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: "temurin"
          cache: "maven"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image with Skaffold
        uses: hiberbee/github-action-skaffold@latest
        id: build
        with:
          working-directory: ${{ github.workspace }}
          file: skaffold.yaml
          command: build
          push: true
          repository: https://index.docker.io/v1/amsidhmicroservice
          tag: "latest"
