name: Build And Deploy on Minikube using Skaffold Github action
on:
  push:
    paths:
      - src/**
      - .github/workflows/skaffold_workflow.yml
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # * is a special character in YAML, so you have to quote this string
    # Runs at 17:30 UTC every day.
    - cron: '30 17 * * *'
    # Run on every 5 minutes
    #- cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build_skaffold:
    name: Skaffold Build Job
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: "temurin"
          cache: "maven"

      - name: Maven Clean and Install
        run: mvn clean install

      - name: Cache layers
        uses: actions/cache@v3
        with:
          path: "${{ github.workspace }}/.skaffold/cache"
          key: skaffold-${{ hashFiles('**/cache') }}
          restore-keys: |
            skaffold-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REPOSITORY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image using skaffold
        uses: hiberbee/github-action-skaffold@latest
        with:
          command: build
          filename: skaffold.yaml
          repository: ${{ secrets.DOCKER_REPOSITORY }}
          working-directory: ${{ github.workspace }}
          skip-tests: true

  run_skaffold:
    name: Skaffold Run Job
    runs-on: ubuntu-22.04
    needs: [ build_skaffold ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Get repositories
        uses: hiberbee/github-action-helm@1.5.0
        with:
          repository-config: helm/repositories.yaml

      - name: Lint chart
        run: helm lint nginx
        working-directory: helm/ms-card-service
