---
apiVersion: v1
kind: ConfigMap
metadata:
  name: card-ms-configmap
  namespace: {{.Values.namespace}}
  labels:
    app: {{default "card-ms-configmap" .Values.configmap.name}}
data:
  SPRING_PROFILES_ACTIVE: {{.Values.configmap.SPRING_PROFILES_ACTIVE}}
  APPLICATION_PORT: "{{.Values.configmap.APPLICATION_PORT}}"
  DATABASE_HOSTNAME: {{.Values.configmap.DATABASE_HOSTNAME}}
  DATABASE_NAME: {{.Values.configmap.DATABASE_NAME}}
  DATABASE_USERNAME: {{.Values.configmap.DATABASE_USERNAME}}
  REDIS_HOST: {{.Values.configmap.REDIS_HOST}}
  REDIS_PORT: "{{.Values.configmap.REDIS_PORT}}"
  REDIS_USERNAME: {{.Values.configmap.REDIS_USERNAME}}
  REDIS_PASSWORD: {{.Values.configmap.REDIS_PASSWORD}}
  ZIPKIN_HOST: {{.Values.configmap.ZIPKIN_HOST}}
  # APM Related Configuration
  ELASTIC_APM_APPLICATION_PACKAGES: {{.Values.configmap.ELASTIC_APM_APPLICATION_PACKAGES}}
  ELASTIC_APM_SECRET_TOKEN: {{.Values.configmap.ELASTIC_APM_SECRET_TOKEN}}
  ELASTIC_APM_SERVER_URLS: {{.Values.configmap.ELASTIC_APM_SERVER_URLS}}
  ELASTIC_APM_SERVICE_NAME: {{.Values.configmap.ELASTIC_APM_SERVICE_NAME}}


